### ISSUE TITLE
Headers already sent (in Request.php Line 143)

### ISSUE THREAD

**Issue by sah-comp** [mikecao/flight#95]
Hello,

with PHP 5.3.28 under Sun OS 5.10 i get a "headers already sent" when handling a POST request. The same code runs well under PHP 5.3.26 on Mac OS and it may have or may not have to do with php://input? Maybe someone can give me a hint, i have no clue.

This is the complete output i get:

Array ( [type] => domain [id] => 0 [lastmodified] => [domain_id] => 14 [name] => about [url] => about [invisible] => 0 [sequence] => 0 [ownPermission] => Array ( [1] => Array ( [type] => permission [id] => 0 [method] => index [sharedRole] => Array ( [1] => Array ( [type] => role [id] => 0 ) [2] => Array ( [type] => role [id] => 0 ) ) ) [2] => Array ( [type] => permission [id] => 0 [method] => add [sharedRole] => Array ( [1] => Array ( [type] => role [id] => 0 ) [2] => Array ( [type] => role [id] => 0 ) ) ) [3] => Array ( [type] => permission [id] => 0 [method] => edit [sharedRole] => Array ( [1] => Array ( [type] => role [id] => 0 ) [2] => Array ( [type] => role [id] => 0 ) ) ) [4] => Array ( [type] => permission [id] => 0 [method] => read [sharedRole] => Array ( [1] => Array ( [type] => role [id] => 0 ) [2] => Array ( [type] => role [id] => 0 ) ) ) [5] => Array ( [type] => permission [id] => 0 [method] => expunge [sharedRole] => Array ( [1] => Array ( [type] => role [id] => 0 ) [2] => Array ( [type] => role [id] => 0 ) ) ) ) [ownDomaini18n] => Array ( [1] => Array ( [type] => domaini18n [id] => 0 [language] => de [name] => Über ) [2] => Array ( [type] => domaini18n [id] => 0 [language] => en [name] => About ) [3] => Array

500 Internal Server Error

session_start(): Cannot send session cache limiter - headers already sent (output started at /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/vendor/mikecao/flight/flight/net/Request.php:143) (2)
#0 [internal function]: flight\Engine->handleError(2, 'session_start()...', '/mnt/webn/b2/51...', 171, Array)
#1 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/src/Controller/Scaffold.php(171): session_start()
#2 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/app/config/routes.php(74): Controller_Scaffold->__construct('/admin', 'domain', '')
#3 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/vendor/mikecao/flight/flight/core/Dispatcher.php(168): {closure}('domain', '', 'table', Object(flight\net\Route))
#4 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/vendor/mikecao/flight/flight/core/Dispatcher.php(143): flight\core\Dispatcher::callFunction(Object(Closure), Array)
#5 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/vendor/mikecao/flight/flight/Engine.php(310): flight\core\Dispatcher::execute(Object(Closure), Array)
#6 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->_start()
#7 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/vendor/mikecao/flight/flight/core/Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#8 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/vendor/mikecao/flight/flight/core/Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#9 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/vendor/mikecao/flight/flight/Engine.php(63): flight\core\Dispatcher->run('start', Array)
#10 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->__call('start', Array)
#11 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/vendor/mikecao/flight/flight/core/Dispatcher.php(191): flight\Engine->start()
#12 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/vendor/mikecao/flight/flight/Flight.php(43): flight\core\Dispatcher::invokeMethod(Array, Array)
#13 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/public/index.php(17): Flight::__callStatic('start', Array)
#14 /mnt/webn/b2/51/51742651/htdocs/helium.limoy.com/public/index.php(17): Flight::start()
#15 {main}

**Comment by sah-comp** [comment]
Hi again, after investigating further i found out that nothing is wrong with Flight here.
